### ISSUE TITLE
[1.19.2] Crash on startup with Immersive Weathering

### ISSUE THREAD

**Issue by qznfbnj** [TeamPancakeMC/BirdsNests#1]
If it's Immersive Weathering's fault, inform me.
[debug.log](https://gist.github.com/qznfbnj/160ed33c8be1547ceff88600c2cabd02#file-debug-log)

![image](https://github.com/TeamPancakeMC/BirdsNests/assets/100760086/8b435167-62e7-4022-b1e0-390fddd5da0e)
## Mod List
![image](https://github.com/TeamPancakeMC/BirdsNests/assets/100760086/ed3bc2ab-f1f3-48bb-983f-4bcaf630219d)

**Comment by XiaoHuNao** [comment]
Repaired
