### ISSUE TITLE
[1.19.2] Crash on startup

### ISSUE THREAD

**Issue by qznfbnj** [TeamPancakeMC/BirdsNests#2]
[debug.log](https://gist.github.com/qznfbnj/7c04e07999b5fe047b1e34dc803c9b19#file-debug-log)

![image](https://github.com/TeamPancakeMC/BirdsNests/assets/100760086/eb3de1bf-6a0c-4aeb-b124-6c867aa59190)
## Mod List
![image](https://github.com/TeamPancakeMC/BirdsNests/assets/100760086/6c13ea24-17df-4a1c-989b-8f91b284017f)

**Comment by qznfbnj** [comment]
好的，控制变量：降级回上次的Forge_43.2.13也不行

JDK 17也不行

**Comment by qznfbnj** [comment]
好吧，改完之后关闭这个问题

**Comment by XiaoHuNao** [comment]
ok
